small ui adjustments
Nitrokey/nitrokey-app2 pull request #92
Opened 2023-06-01 13:34 UTC by Niklap97

- make nk3 button scalable
- center the messageboxes accordingly
- center logo
- remove stylesheet colors

2023-06-06 10:57 UTC, daringer approved these changes

2023-06-13 11:39 UTC, robin-nitrokey commented on nitrokeyapp/update.py
> +        self.parent = overview_tab.parent_ui
Can’t we just use `overview_tab`?

2023-06-14 14:46 UTC, robin-nitrokey commented
The button is still truncated for me (even with a bigger window size):

![app](https://github.com/Nitrokey/nitrokey-app2/assets/81762114/76fb8bd5-b9cc-4bac-9ddc-d5634d5dcc2e)

2023-06-14 15:48 UTC, Niklap97 commented on nitrokeyapp/update.py
> +        self.parent = overview_tab.parent_ui
yes, thanks for pointing this out!

2023-06-14 15:55 UTC, Niklap97 commented
did you rebuild the ui files with `make build-ui` ?

2023-06-15 07:12 UTC, robin-nitrokey commented
> did you rebuild the ui files with `make build-ui` ?

I must have missed that.  Looks good!

2023-06-26 18:40 UTC, robin-nitrokey requested changes
Please add `qt_material` to the mypy whitelist to fix the CI.

2023-06-26 18:44 UTC, robin-nitrokey commented
I think the difference between enabled and disabled icons is a bit too subtle with the default settings, but we can address that later.
![1](https://github.com/Nitrokey/nitrokey-app2/assets/81762114/ea78d189-eab6-4dcd-9b75-c46eb02c983d)

2023-06-27 10:03 UTC, robin-nitrokey approved these changes

2023-06-27 11:03 UTC, merged